spring:
  application:
    name: auth-service

  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/authservice

  flyway:
    user: user
    password: password
    url: jdbc:postgresql://localhost:5432/authservice

logging:
  level:
    org.springframework: DEBUG