spring:
  application:
    name: auth-service

  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: ${POSTGRES_URL}

  flyway:
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: ${POSTGRES_URL}

logging:
  level:
    org.springframework: DEBUG