spring:
  application:
    name: auth-service

  datasource:
    username: ${POSTGRES_USER:user}
    password: ${POSTGRES_PASSWORD:password}
    url: ${POSTGRES_URL:jdbc:postgresql://postgres:5432/authservice}

  flyway:
    user: ${POSTGRES_USER:user}
    password: ${POSTGRES_PASSWORD:password}
    url: ${POSTGRES_URL:jdbc:postgresql://postgres:5432/authservice}

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
  endpoint:
    prometheus:
        enabled: true
  metrics:
    enable:
      all: true
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    org.springframework: DEBUG